name: $(BuildDefinitionName)_$(year:yy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- main
- release/*

pool:
  name: BUILD-DOTNET-01

variables:  
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  targetBuildFolder: '$(dropfolder)'
  targetDeployFolder: '$(deployFolder)'
  projectKey: 'sh-devops-service-now-cli'
  majorVersion: '1'
  minorVersion: '0'
  patchVersion: '0'
  version: '$(majorVersion).$(minorVersion).$(patchVersion)'


stages:
  - stage: Build
    displayName: Build
    jobs:
    - job: Build
      steps:
      - task: NuGetToolInstaller@0

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: SonarQubePrepare@5
        displayName: 'Prepare the SonarQube analysis'
        inputs:
          SonarQube: 'SonarQube'
          scannerMode: 'MSBuild'
          projectKey: '$(projectKey)'
          projectName: '$(projectKey)'
          projectVersion: '$(Build.BuildNumber)'
        continueOnError: false

      - task: richardfennellbm.BM-VSTS-Versioning-Task.Version-DotNetCoreAssemblies-Task.VersionDotNetCoreAssemblies@3
        displayName: 'Version .NET Core Assemblies'
        inputs:
          AddDefault: true

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: VSTest@2
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: SonarQubeAnalyze@5

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**\bin\$(BuildConfiguration)\**'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          publishLocation: FilePath
          TargetPath: '$(targetBuildFolder)\$(Build.BuildNumber)'
        condition: succeeded()

  - template: deploy-stage-template.yml
    parameters:
      environment: 'Test'
      configGroup: 'cli-config Test'
      buildFolder: '$(targetBuildFolder)'
      deployFolder: '$(targetDeployFolder)'

  - template: deploy-stage-template.yml
    parameters:
      environment: 'Prod'
      configGroup: 'cli-config Prod'
      buildFolder: '$(targetBuildFolder)'
      deployFolder: '$(targetDeployFolder)'