parameters:
  environment: ''
  configGroup: ''
  buildFolder: ''
  deployFolder: ''

stages:
  - stage: Deploy${{ parameters.environment }}
    variables:
      - group: ${{ parameters.configGroup }}
    displayName: 'Deploy ${{ parameters.environment }} environment'
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
    - deployment: DeployJob
      displayName: 'Deploy CLI'
      environment: 
        name: ${{ parameters.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            - task: CopyFiles@2
              displayName: 'Copy to Common Folder'
              inputs:
                SourceFolder: '${{ parameters.buildFolder }}\$(Build.BuildNumber)\drop\src\ServiceNowCLI\bin\$(BuildConfiguration)\net8.0-windows\'
                Contents: '*.*'
                TargetFolder: '$(parameters.deployFolder)\${{ parameters.environment }}'
                CleanTargetFolder: true
                OverWrite: true
            - task: FileTransform@2
              displayName: 'Set Configuration Values'
              inputs:
                folderPath: '$(parameters.deployFolder)\${{ parameters.environment }}'
                xmlTargetFiles: 'ServiceNowCLI.dll.config'