namespace ServiceNowCLI.Core.ServiceNow
{
    public class SnChangeRequestResponseModel
    {
        public BaseLink assignment_group { get; set; }
        public BaseLink business_service { get; set; }
        public BaseLink chg_model { get; set; }
        public BaseLink closed_by { get; set; }
        public BaseLink opened_by { get; set; }
        public BaseLink requested_by { get; set; }
        public BaseLink std_change_producer_version { get; set; }
        public BaseLink sys_domain { get; set; }
        public string active { get; set; }
        public string activity_due { get; set; }
        public string additional_assignee_list { get; set; }
        public string approval { get; set; }
        public string approval_history { get; set; }
        public string assigned_to { get; set; }
        public string backout_plan { get; set; }
        public string business_duration { get; set; }
        public string cab_date_time { get; set; }
        public string cab_delegate { get; set; }
        public string cab_recommendation { get; set; }
        public string cab_required { get; set; }
        public string calendar_duration { get; set; }
        public string category { get; set; }
        public string change_plan { get; set; }
        public string ci_class { get; set; }
        public string close_code { get; set; }
        public string close_notes { get; set; }
        public string closed_at { get; set; }
        public string comments { get; set; }
        public string comments_and_work_notes { get; set; }
        public string company { get; set; }
        public string conflict_last_run { get; set; }
        public string conflict_status { get; set; }
        public string contact_type { get; set; }
        public string contract { get; set; }
        public string correlation_display { get; set; }
        public string correlation_id { get; set; }
        public string description { get; set; }
        public string due_date { get; set; }
        public string end_date { get; set; }
        public string escalation { get; set; }
        public string expected_start { get; set; }
        public string follow_up { get; set; }
        public string group_list { get; set; }
        public string impact { get; set; }
        public string implementation_plan { get; set; }
        public string is_bulk { get; set; }
        public string justification { get; set; }
        public string knowledge { get; set; }
        public string location { get; set; }
        public string made_sla { get; set; }
        public string number { get; set; }
        public string on_hold { get; set; }
        public string on_hold_reason { get; set; }
        public string on_hold_task { get; set; }
        public string opened_at { get; set; }
        public string order { get; set; }
        public string parent { get; set; }
        public string phase { get; set; }
        public string phase_state { get; set; }
        public string priority { get; set; }
        public string probability { get; set; }
        public string production_system { get; set; }
        public string proposed_change { get; set; }
        public string reason { get; set; }
        public string reassignment_count { get; set; }
        public string requested_by_date { get; set; }
        public string review_comments { get; set; }
        public string review_date { get; set; }
        public string review_status { get; set; }
        public string risk { get; set; }
        public string risk_impact_analysis { get; set; }
        public string risk_value { get; set; }
        public string route_reason { get; set; }
        public string scope { get; set; }
        public string service_offering { get; set; }
        public string short_description { get; set; }
        public string sla_due { get; set; }
        public string start_date { get; set; }
        public string state { get; set; }
        public string sys_class_name { get; set; }
        public string sys_created_by { get; set; }
        public string sys_created_on { get; set; }
        public string sys_domain_path { get; set; }
        public string sys_id { get; set; }
        public string sys_mod_count { get; set; }
        public string sys_tags { get; set; }
        public string sys_updated_by { get; set; }
        public string sys_updated_on { get; set; }
        public string task_effective_number { get; set; }
        public string test_plan { get; set; }
        public string time_worked { get; set; }
        public string type { get; set; }
        public string u_retrospective_change { get; set; }
        public string unauthorized { get; set; }
        public string universal_request { get; set; }
        public string upon_approval { get; set; }
        public string upon_reject { get; set; }
        public string urgency { get; set; }
        public string user_input { get; set; }
        public string watch_list { get; set; }
        public string work_end { get; set; }
        public string work_start { get; set; }
        public string x_mioms_azpipeline_build_id { get; set; }
        public string x_mioms_azpipeline_pipeline_metadata { get; set; }
        public string x_mioms_azpipeline_stage_attempt { get; set; }
        public string x_mioms_azpipeline_stage_id { get; set; }
        public string x_mioms_azpipeline_template_id { get; set; }
    }

    public class BaseLink
    {
        public string link { get; set; }
        public string value { get; set; }
    }
}
